export const Cars = [
  {
    id: 1,
    model: "Toyota",
    color: "White",
    year: 2018,
    price: 5000,
    mileage: 45000,
    trim: "Coupe",
    transmission: "Automatic",
    fuelType: "Gasoline",
    driveType: "FWD",
    mpgHighway: 45,
    cylinders: 4,
    image: "https://vehicle-images.dealerinspire.com/stock-images/thumbnails/large/chrome/195fc18dbb488debdc22325994b0a2b6.png",
  },
  {
    id: 2,
    model: "Honda",
    color: "Black",
    year: 2019,
    price: 4000,
    mileage: 30000,
    trim: "Sedan",
    transmission: "Manual",
    fuelType: "Hybrid",
    driveType: "AWD",
    mpgHighway: 60,
    cylinders: 6,
    image: "https://cars.usnews.com/static/images/Auto/izmo/i3380282/2017_honda_civic_angularfront.jpg",
  },
  {
    id: 3,
    model: "Ford",
    color: "Blue",
    year: 2020,
    price: 3000,
    mileage: 52000,
    trim: "Van",
    transmission: "Automatic",
    fuelType: "Diesel",
    driveType: "4WD",
    mpgHighway: 35,
    cylinders: 8,
    image: "https://www.autocar.co.uk/sites/autocar.co.uk/files/images/car-reviews/first-drives/legacy/fordgofurther2016_mustang_03.jpg",
  },
  {
    id: 4,
    model: "Chevrolet",
    color: "Gray",
    year: 2021,
    price: 200,
    mileage: 12000,
    trim: "Hatchback",
    transmission: "Manual",
    fuelType: "Electric",
    driveType: "RWD",
    mpgHighway: 120,
    cylinders: 4,
    image: "https://platform.cstatic-images.com/in/v2/stock_photos/017adca0-2270-476f-ad0d-20b7804522d1/137ddc7d-2521-4fc1-9c20-355409c34c27.png",
  },
  {
    id: 5,
    model: "BMW",
    color: "Red",
    year: 2022,
    price: 7000,
    mileage: 18000,
    trim: "Coupe",
    transmission: "Automatic",
    fuelType: "Gasoline",
    driveType: "AWD",
    mpgHighway: 55,
    cylinders: 6,
    image: "https://cache.bmwusa.com/cosy.arox?pov=walkaround&client=byo&vehicle=203O&paint=P0A75&brand=WBBM&sa=S01T4,S01T4,S0302,S03MB,S0403,S0465,S0775,S07AC&RESP=PNG&quality=90&width=900&sharpness=100&BKGND=TRANSPARENT&angle=30",
  },
  {
    id: 6,
    model: "Audi",
    color: "Red",
    year: 2023,
    price: 35000,
    mileage: 7000,
    trim: "Sedan",
    transmission: "Manual",
    fuelType: "Hybrid",
    driveType: "FWD",
    mpgHighway: 70,
    cylinders: 4,
    image: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Audi/A4/10548/1757137106350/front-left-side-47.jpg",
  },
  {
    id: 7,
    model: "Mercedes",
    color: "White",
    year: 2018,
    price: 40000,
    mileage: 67000,
    trim: "Van",
    transmission: "Automatic",
    fuelType: "Diesel",
    driveType: "4WD",
    mpgHighway: 30,
    cylinders: 12,
    image: "https://www.edmunds.com/assets/m/for-sale/db-w1kaf4gb4rr236408/img-1-600x400.jpg",
  },
  {
    id: 8,
    model: "Toyota",
    color: "Black",
    year: 2020,
    price: 2000,
    mileage: 85000,
    trim: "Hatchback",
    transmission: "Manual",
    fuelType: "Gasoline",
    driveType: "AWD",
    mpgHighway: 50,
    cylinders: 6,
    image: "https://toyotasialkot.com/wp-content/uploads/2022/04/attitube-black.png",
  },
  {
    id: 9,
    model: "Audi",
    color: "Black",
    year: 2019,
    price: 700,
    mileage: 95000,
    trim: "Coupe",
    transmission: "Automatic",
    fuelType: "Electric",
    driveType: "RWD",
    mpgHighway: 150,
    cylinders: 4,
    image: "https://zffautomotive.ie/wp-content/uploads/2024/08/1-3.jpeg",
  },
  {
    id: 10,
    model: "Honda",
    color: "Blue",
    year: 2021,
    price: 500,
    mileage: 15000,
    trim: "Sedan",
    transmission: "Manual",
    fuelType: "Gasoline",
    driveType: "FWD",
    mpgHighway: 40,
    cylinders: 6,
    image: "https://di-uploads-pod11.dealerinspire.com/valleyhonda/uploads/2019/11/2020-Civic-Sedan-Aegean-Blue-Metallic.png",
  },
];
